ci: delete dead code, rename variables

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -434,9 +434,9 @@ jobs:
           command: |
             pnpm snapshots
             if [ "$(git diff --exit-code snapshots)" ]; then
-              [ -z "$(git ls-files --others --exclude-standard snapshots)" ] || echo "export ABI_SNAPSHOT_STATUS=1" >> "$BASH_ENV"
+              [ -z "$(git ls-files --others --exclude-standard snapshots)" ] || echo "export SNAPSHOTS_STATUS=1" >> "$BASH_ENV"
             else
-              echo "export ABI_SNAPSHOT_STATUS=1" >> "$BASH_ENV"
+              echo "export SNAPSHOTS_STATUS=1" >> "$BASH_ENV"
             fi
           working_directory: packages/contracts-bedrock
       - run:
@@ -450,10 +450,6 @@ jobs:
               FAILED=1
               echo "Gas snapshot failed, see job output for details."
             fi
-            if [[ "$STORAGE_SNAPSHOT_STATUS" -ne 0 ]]; then
-              echo "Storage snapshot failed, see job output for details."
-              FAILED=1
-            fi
             if [[ "$SEMVER_LOCK_STATUS" -ne 0 ]]; then
               echo "Semver lock failed, see job output for details."
               FAILED=1
@@ -466,8 +462,8 @@ jobs:
               echo "Deploy config check failed, see job output for details."
               FAILED=1
             fi
-            if [[ "$ABI_SNAPSHOT_STATUS" -ne 0 ]]; then
-              echo "ABI snapshot check failed, see job output for details."
+            if [[ "$SNAPSHOTS_STATUS" -ne 0 ]]; then
+              echo "Snapshots check failed, see job output for details."
               FAILED=1
             fi
             if [[ "$FAILED" -ne 0 ]]; then
