Introduce dispute game contracts as a smart contracts package.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -339,6 +339,30 @@ jobs:
             FOUNDRY_PROFILE: ci
           working_directory: packages/contracts-bedrock
 
+    contracts-dispute-tests:
+      docker:
+        - image: us-docker.pkg.dev/oplabs-tools-artifacts/images/ci-builder:latest
+      resource_class: large
+      steps:
+        - checkout
+        - attach_workspace: { at: "." }
+        - restore_cache:
+            name: Restore Yarn Package Cache
+            keys:
+              - yarn-packages-v2-{{ checksum "yarn.lock" }}
+        - check-changed:
+            patterns: contracts-dispute
+        - run:
+            name: print forge version
+            command: forge --version
+            working_directory: packages/contracts-dispute
+        - run:
+            name: run tests
+            command: yarn test
+            environment:
+              FOUNDRY_PROFILE: ci
+            working_directory: packages/contracts-dispute
+
   contracts-bedrock-checks:
     docker:
       - image: us-docker.pkg.dev/oplabs-tools-artifacts/images/ci-builder:latest
@@ -409,6 +433,111 @@ jobs:
             if [[ "$FAILED" -ne 0 ]]; then
               exit 1
             fi
+
+  contracts-dispute-checks:
+<<<<<<< HEAD
+=======
+    docker:
+      - image: ethereumoptimism/ci-builder:latest
+    steps:
+      - checkout
+      - attach_workspace: { at: "." }
+      - restore_cache:
+          name: Restore Yarn Package Cache
+          keys:
+            - yarn-packages-v2-{{ checksum "yarn.lock" }}
+      - check-changed:
+          patterns: contracts-dispute
+      - run:
+          name: lint
+          command: |
+            yarn lint:check || echo "export LINT_STATUS=1" >> "$BASH_ENV"
+          working_directory: packages/contracts-dispute
+      - run:
+          name: gas snapshot
+          command: |
+            forge --version
+            yarn gas-snapshot --check || echo "export GAS_SNAPSHOT_STATUS=1" >> "$BASH_ENV"
+          environment:
+            FOUNDRY_PROFILE: ci
+          working_directory: packages/contracts-dispute
+      - run:
+          name: storage snapshot
+          command: |
+            yarn storage-snapshot
+            git diff --exit-code .storage-layout || echo "export STORAGE_SNAPSHOT_STATUS=1" >> "$BASH_ENV"
+          working_directory: packages/contracts-dispute
+      - run:
+          name: check statuses
+          command: |
+            if [[ "$LINT_STATUS" -ne 0 ]]; then
+              FAILED=1
+              echo "Linting failed, see job output for details."
+            fi
+            if [[ "$GAS_SNAPSHOT_STATUS" -ne 0 ]]; then
+              FAILED=1
+              echo "Gas snapshot failed, see job output for details."
+            fi
+            if [[ "$STORAGE_SNAPSHOT_STATUS" -ne 0 ]]; then
+              echo "Storage snapshot failed, see job output for details."
+              FAILED=1
+            fi
+            if [[ "$FAILED" -ne 0 ]]; then
+              exit 1
+            fi
+
+
+  contracts-bedrock-slither:
+>>>>>>> 4a57dc6bb (feat(contracts-dispute): Naive Bond Manager [PoPs] (#5517))
+    docker:
+      - image: ethereumoptimism/ci-builder:latest
+    steps:
+      - checkout
+      - attach_workspace: { at: "." }
+      - restore_cache:
+          name: Restore Yarn Package Cache
+          keys:
+            - yarn-packages-v2-{{ checksum "yarn.lock" }}
+      - check-changed:
+          patterns: contracts-dispute
+      - run:
+          name: lint
+          command: |
+            yarn lint:check || echo "export LINT_STATUS=1" >> "$BASH_ENV"
+          working_directory: packages/contracts-dispute
+      - run:
+          name: gas snapshot
+          command: |
+            forge --version
+            yarn gas-snapshot --check || echo "export GAS_SNAPSHOT_STATUS=1" >> "$BASH_ENV"
+          environment:
+            FOUNDRY_PROFILE: ci
+          working_directory: packages/contracts-dispute
+      - run:
+          name: storage snapshot
+          command: |
+            yarn storage-snapshot
+            git diff --exit-code .storage-layout || echo "export STORAGE_SNAPSHOT_STATUS=1" >> "$BASH_ENV"
+          working_directory: packages/contracts-dispute
+      - run:
+          name: check statuses
+          command: |
+            if [[ "$LINT_STATUS" -ne 0 ]]; then
+              FAILED=1
+              echo "Linting failed, see job output for details."
+            fi
+            if [[ "$GAS_SNAPSHOT_STATUS" -ne 0 ]]; then
+              FAILED=1
+              echo "Gas snapshot failed, see job output for details."
+            fi
+            if [[ "$STORAGE_SNAPSHOT_STATUS" -ne 0 ]]; then
+              echo "Storage snapshot failed, see job output for details."
+              FAILED=1
+            fi
+            if [[ "$FAILED" -ne 0 ]]; then
+              exit 1
+            fi
+
 
   contracts-bedrock-slither:
     docker:
