ci: add ctb abi-spec status check

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -433,6 +433,12 @@ jobs:
             git diff --exit-code ./invariant-docs/*.md || echo "export INVARIANT_DOCS_STATUS=1" >> "$BASH_ENV"
           working_directory: packages/contracts-bedrock
       - run:
+          name: ABI spec
+          command: |
+            pnpm abi-spec
+            git diff --exit-code .abi-spec.json || echo "export ABI_SPEC_STATUS=1" >> "$BASH_ENV"
+          working_directory: packages/contracts-bedrock
+      - run:
           name: check statuses
           command: |
             if [[ "$LINT_STATUS" -ne 0 ]]; then
@@ -457,6 +463,10 @@ jobs:
             fi
             if [[ "$DEPLOY_CONFIGS_STATUS" -ne 0 ]]; then
               echo "Deploy config check failed, see job output for details."
+              FAILED=1
+            fi
+            if [[ "$ABI_SPEC_STATUS" -ne 0 ]]; then
+              echo "ABI spec failed, see job output for details."
               FAILED=1
             fi
             if [[ "$FAILED" -ne 0 ]]; then
